using Shop111.Constants;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Shop111.Models.DTOs;

namespace Shop111.Repositories
{
    public class CartRepository : ICartRepository
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public CartRepository(ApplicationDbContext db, IHttpContextAccessor httpContextAccessor,
            UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
            _httpContextAccessor = httpContextAccessor;
        }
        public async Task<int> AddItem(int productId, int qty)
        {
            // we will use transaction here because we have to do multiple operations and if any of the operation fails then we have to rollback the transaction
            // প্রোডাক্টের সাথে ভেন্ডরের স্ট্যাটাস চেক করা
            var productInfo = await _db.Products
                .Include(p => p.Vendor)
                .FirstOrDefaultAsync(p => p.Id == productId);

            if (productInfo?.Vendor != null && !productInfo.Vendor.IsLive)
            {
                throw new InvalidOperationException("এই ভেন্ডরটি বর্তমানে নিষ্ক্রিয়। আপনি তাদের প্রোডাক্ট অর্ডার করতে পারবেন না।");
            }
            // we will use transaction here because we have to do multiple operations and if any of the operation fails then we have to rollback the transaction
            string userId = GetUserId();
            using var transaction = await _db.Database.BeginTransactionAsync();
            try
            {
                if (string.IsNullOrEmpty(userId))
                    throw new UnauthorizedAccessException("user is not logged-in");

                var cart = await GetCart(userId);

                if (cart is null)
                {
                    cart = new ShoppingCart { UserId = userId };
                    _db.ShoppingCarts.Add(cart);
                }

                await _db.SaveChangesAsync();  // So that we can retrieve cart.Id which is generated by db 
                // cart detail section
                var cartItem = _db.CartDetails
                                  .FirstOrDefault(a => a.ShoppingCartId == cart.Id && a.ProductId == productId);
                if (cartItem is not null)
                {
                    cartItem.Quantity += qty;
                }
                else
                {
                    var product = _db.Products.Find(productId)
                                ?? throw new ArgumentException("product not found");

                    cartItem = new CartDetail
                    {
                        ProductId = productId,
                        ShoppingCartId = cart.Id,
                        Quantity = qty,
                        UnitPrice = product.Price
                    };
                    _db.CartDetails.Add(cartItem);
                }
                await _db.SaveChangesAsync();
                await transaction.CommitAsync();

                var cartItemCount = await GetCartItemCount(userId);
                return cartItemCount;
            }
            catch (Exception ex)
            {
                throw;
            }

        }


        public async Task<int> RemoveItem(int productId)
        {
            string userId = GetUserId();
            try
            {
                if (string.IsNullOrEmpty(userId))
                    throw new UnauthorizedAccessException("user is not logged-in");

                var cart = await GetCart(userId);
                if (cart is null)
                    throw new InvalidOperationException("Invalid cart");

                // cart detail section
                var cartItem = _db.CartDetails
                                  .FirstOrDefault(a => a.ShoppingCartId == cart.Id && a.ProductId == productId);
                if (cartItem is null)
                    throw new InvalidOperationException("Not items in cart");
                else if (cartItem.Quantity == 1)
                    _db.CartDetails.Remove(cartItem);
                else
                    cartItem.Quantity--;
                await _db.SaveChangesAsync();

                var cartItemCount = await GetCartItemCount(userId);
                return cartItemCount;
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public async Task<ShoppingCart> GetUserCart()
        {
            var userId = GetUserId();
            if (userId == null)
                throw new InvalidOperationException("Invalid userid");
            var shoppingCart = await _db.ShoppingCarts
                                  .Include(a => a.CartDetails)
                                  .ThenInclude(a => a.Product)
                                  .ThenInclude(a => a.Stock)
                                  .Include(a => a.CartDetails)
                                  .ThenInclude(a => a.Product)
                                  .ThenInclude(a => a.Genre)
                                  .Where(a => a.UserId == userId)
                                  .AsNoTracking()
                                  .FirstOrDefaultAsync();
            return shoppingCart;

        }
        public async Task<ShoppingCart> GetCart(string userId)
        {
            var cart = await _db.ShoppingCarts.FirstOrDefaultAsync(x => x.UserId == userId);
            return cart;
        }

        public async Task<int> GetCartItemCount(string userId = "")
        {
            if (string.IsNullOrEmpty(userId))
            {
                userId = GetUserId();
            }
            var data = await _db.ShoppingCarts
                                .Include(c => c.CartDetails)
                                .Where(c => c.UserId == userId)
                                .SelectMany(c => c.CartDetails)
                                .CountAsync();
            return data;

            //OR

            //var data = await (from cart in _db.ShoppingCarts
            //                  join cartDetail in _db.CartDetails
            //                  on cart.Id equals cartDetail.ShoppingCartId
            //                  where cart.UserId == userId
            //                  select new { cartDetail.Id }
            //                  ).ToListAsync();
            //return data.Count;
        }

        public async Task<bool> DoCheckout(CheckoutModel model)

        {
            using var transaction = await _db.Database.BeginTransactionAsync();
            try
            {
                // logic
                // move data from cartDetail to order and order detail then we will remove cart detail
                var userId = GetUserId();
                if (string.IsNullOrEmpty(userId))
                    throw new UnauthorizedAccessException("User is not logged-in");

                var cart = await GetCart(userId);
                if (cart is null)
                    throw new InvalidOperationException("Invalid cart");

                var cartDetail = _db.CartDetails
                                    .Where(a => a.ShoppingCartId == cart.Id).ToList();
                if (cartDetail.Count == 0)
                    throw new InvalidOperationException("Cart is empty");
                //var pendingRecord = _db.OrderStatuses.FirstOrDefault(s => s.StatusName == "Pending");
                //if (pendingRecord is null)
                //    throw new Exception("Order status does not have Pending status");

                var order = new Order
                {
                    UserId = userId,
                    CreateDate = DateTime.UtcNow,
                    Name = model.Name,
                    Email = model.Email,
                    MobileNumber = model.MobileNumber,
                    PaymentMethod = model.PaymentMethod,
                    Address = model.Address,
                    IsPaid = false,
                    OrderStatus = EOrderStatus.Pending,

                };
                _db.Orders.Add(order);
                await _db.SaveChangesAsync();

                foreach (var item in cartDetail)
                {
                    var orderDetail = new OrderDetail
                    {
                        ProductId = item.ProductId,
                        OrderId = order.Id,
                        Quantity = item.Quantity,
                        UnitPrice = item.UnitPrice,
                        Order = order
                    };
                    _db.OrderDetails.Add(orderDetail);

                    // update stock here

                    var stock = await _db.Stocks.FirstOrDefaultAsync(a => a.ProductId == item.ProductId);
                    if (stock == null)
                    {
                        throw new InvalidOperationException("Stock is null");
                    }

                    if (item.Quantity > stock.Quantity)
                    {
                        throw new InvalidOperationException($"Only {stock.Quantity} items(s) are available in the stock");
                    }
                    // decrease the number of quantity from the stock table
                    stock.Quantity -= item.Quantity;
                }

                // removing the cartdetails
                _db.CartDetails.RemoveRange(cartDetail);

                await _db.SaveChangesAsync();

                await transaction.CommitAsync();
                return true;
            }
            catch
            {
                throw;

            }
        }

        private string GetUserId()
        {
            var principal = _httpContextAccessor.HttpContext.User;
            string userId = _userManager.GetUserId(principal);
            return userId;
        }


    }
}



